### ISSUE TITLE
[Feature Request] Can it respond to window resize?

### ISSUE THREAD

**Issue by christian-byrne** [OliverCrosby/Comfyui-Minimap#11]
I am on Ubuntu / Chrome with ComfyUI_frontend version 1.2.31. When I resize the window or increase browser zoom, the minimap can get stuck offscreen as it doesn't re-position on these events for me. Thank you!

**Comment by OliverCrosby** [comment]
This is a feature I would like to add. Basically I just have to change the x/y coordinates of the map from an absolute pixel to a percentage of the viewport. Should be simple but I gave this a shot last night and it didn't work. Will try again soon.

**Comment by christian-byrne** [comment]
The frontend exposes a ResizeObserver on global scope:

![Selection_287](https://github.com/user-attachments/assets/d3927305-b684-4f63-ada5-034a89cd0664)

For example, the main app.js subscribes to ResizeObserver and passes this callback:

https://github.com/Comfy-Org/ComfyUI_frontend/blob/3d041dd742cd661bbd1c548e7929214349fa86cf/src/scripts/app.ts#L1950-L1960

Have to only account for DPI when DPI > 1:

https://github.com/Comfy-Org/ComfyUI_frontend/blob/3d041dd742cd661bbd1c548e7929214349fa86cf/src/scripts/app.ts#L3006-L3010

**Comment by OliverCrosby** [comment]
Fixed by @sn0w12.

If the minimap is out of bounds it should snap back into the viewport. 

https://github.com/OliverCrosby/Comfyui-Minimap/pull/12#issue-2481954405
